function [fitresult, gof] = createFit(R, T)
%CREATEFIT(R,T)
%  Create a fit.
%
%  Data for 'TfromR' fit:
%      X Input : R
%      Y Output: T
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Aug-2016 11:00:37


%% Fit: 'TfromR'.
[xData, yData] = prepareCurveData( R, T );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'TfromR' );
h = plot( fitresult, xData, yData );
legend( h, 'T vs. R', 'TfromR', 'Location', 'NorthEast' );
% Label axes
xlabel( 'R' );
ylabel( 'T' );
grid on


